name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gcp Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Install node dependencies
        run: npm ci
      - name: Deploy to google cloud
        run: |
          gcloud config set project ns-tracker-app
          gcloud app deploy app.yaml --quiet
